### ISSUE TITLE
For me ulauncher just shows "loading" next to a single maim icon 

### ISSUE THREAD

**Issue by adrianocr** [noam09/ulauncher-maim#1]
If I type "m" in ulauncher, I get the following and nothing else: 

![Screenshot from 2019-07-29 19-13-59](https://user-images.githubusercontent.com/7603338/62088957-13666800-b235-11e9-8054-236240f4f650.png)

It never actually loads

**Comment by noam09** [comment]
Somehow I completely missed all issues in this repository, I'll have to look into it. 🤷‍♂️ (EDIT: apparently I wasn't Watching this repo, I must have accidentally clicked the Watch button)
Sorry for the delay @adrianocr, and thank you @mohammedmatar for the fix!
