### ISSUE TITLE
Delay setting is not an integer

### ISSUE THREAD

**Issue by thejspr** [noam09/ulauncher-maim#4]
It's not working for me, and I'm getting this error:

```
ERROR:__main__:Delay setting is not an integer: name 'long' is not defined
com.github.noam09.ulauncher-maim | 2020-04-13 14:56:30,535 | ERROR | __main__: on_event() | Delay setting is not an integer: name 'long' is not defined
terminate called after throwing an instance of 'cxxopts::option_not_exists_exception'
  what():  Option ‘capturebackground’ does not exist
Aborted (core dumped)
```

I've tried changing the delay value, but the problem persists.

I'm using the latest commit, and ulauncher v.5.7.3 on Ubuntu 19.10.

**Comment by noam09** [comment]
Hey @thejspr, sorry for the delay. I wasn't receiving notifications.
Assuming you haven't given up on this extension, please check if the latest version fixes the issue.
